/** Barrel export for the shared UI primitives. Import via `@/components/ui`. */
export { Button } from "./Button";
export { Card } from "./Card";
export { CardRail } from "./CardRail";
export { Chip } from "./Chip";
export { ConfirmDialog } from "./ConfirmDialog";
export { Container } from "./Container";
export { EmptyState } from "./EmptyState";
export { FormError } from "./FormError";
export { ContentCard } from "./ContentCard";
export type { ContentCardProps, ContentCardLayout, ContentTag } from "./ContentCard";
export { GoalTile } from "./GoalTile";
export { IconBadge } from "./IconBadge";
export { IllustrationPlaceholder } from "./IllustrationPlaceholder";
export { Input } from "./Input";
export { Pagination } from "./Pagination";
export { Pill } from "./Pill";
export { ProgressDots } from "./ProgressDots";
export { Select } from "./Select";
export { SectionHeader } from "./SectionHeader";
export { SelectableCard, selectableSurface } from "./SelectableCard";
export { Skeleton } from "./Skeleton";
export { SlideControls } from "./SlideControls";
export type { SlideControlsProps } from "./SlideControls";
export { SubjectCard } from "./SubjectCard";
export { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "./Table";
export { Toggle } from "./Toggle";
